### ISSUE TITLE
velocity parameter

### ISSUE THREAD

**Issue by damianpri** [leommxj/gr-adsbout#1]
Hello, I am interested in the project. I am interested in achieving the value of speed in transmission.

Do you have an extra reference to share and continue with the development?

Thank you

**Comment by leommxj** [comment]
I found The 1090MHz Riddle is quite helpful, info about velocity message is here: [Airborne Velocity
](https://mode-s.org/decode/adsb/airborne-velocity.html). 
To achieve sending of the value of speed we need to implement a function to generate the desired type message in ModeS class at `python/adsb_encoder.py`, and a source block to call it to generate the signal. It wouldn't be hard I think.

**Comment by gabrielb1804** [comment]
I know this is 4 years old, but with the port to gnuradio 3.10 could there be an inclusion of velocity functionality?
